name: 'Apply Terraform'
description: 'Apply Terraform Using Google OIDC'
inputs:
  cosmos_name:
    description: 'Cosmos name'
    required: true
  realm_name:
    description: 'Realm name'
    required: true
  foundation_name:
    description: 'Foundation name'
    required: true
  app_name:
    description: 'Application name'
    required: true
  env_name:
    description: 'Environment Name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init
      shell: bash
      run: |
        terraform -chdir=iac/environments/base init \
        -backend-config="bucket=${{ inputs.cosmos_name }}" \
        -backend-config="prefix=${{ inputs.realm_name }}/_/${{ inputs.foundation_name }}/${{ inputs.app_name }}/${{ inputs.env_name }}/terraform/state"

    - name: Terraform plan
      shell: bash
      run: |
        terraform -chdir=iac/environments/base apply -auto-approve
