# dataset_id: sample_dataset_1
# description: Sample Dataset 1
# friendly_name: Sample Dataset
# location: eu
# delete_contents_on_destroy: false
# default_partition_expiration_ms: 5184000000  # Might need this for project without billing
# default_table_expiration_ms: 5184000000  # Might need this for project without billing