name: Workflow - dev

on:
  push:
    tags:
    - '*'

jobs:
  deploy:
    if: true
    environment: dev
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - id: checkout-code
      uses: actions/checkout@v4

    - id: publish-pypi
      name: Publish PYPI
      uses: ./.github/actions/module-pypi/publish-pypi

  remote-test:
    if: false
    environment: dev
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - id: checkout-code
      uses: actions/checkout@v4
